export const GET_ALLCOMMENTS_REQUEST = "GET_ALLCOMMENTS_REQUEST";
export const GET_AllCOMMENTS_SUCCESS = "GET_AllCOMMENTS_SUCCESS";
export const GET_ALLCOMMENTS_FAIL = "GET_ALLCOMMENTS_FAIL";
export const GET_ALLCOMMENTS_RESET = "GET_ALLCOMMENTS_RESET";

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL'
export const COMMENT_CREATE_RESET = 'COMMENT_CREATE_RESET'

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST'
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS'
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL'
export const COMMENT_DELETE_RESET = 'COMMENT_DELETE_RESET'

export const SUBSCRIBER_UPDATE_REQUEST = 'SUBSCRIBER_UPDATE_REQUEST'
export const SUBSCRIBER_UPDATE_SUCCESS = 'SUBSCRIBER_UPDATE_SUCCESS'
export const SUBSCRIBER_UPDATE_FAIL = 'SUBSCRIBER_UPDATE_FAIL'
export const SUBSCRIBER_UPDATE_RESET = 'SUBSCRIBER_UPDATE_RESET'


export const SUBSCRIBER_DETAILS_REQUEST = 'SUBSCRIBER_DETAILS_REQUEST'
export const SUBSCRIBER_DETAILS_SUCCESS = 'SUBSCRIBER_DETAILS_SUCCESS'
export const SUBSCRIBER_DETAILS_FAIL = 'SUBSCRIBER_DETAILS_FAIL'
export const SUBSCRIBER_DETAILS_RESET= 'SUBSCRIBER_DETAILS_RESET'
